;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Ability.Attack",DevComment="")
GameplayTagList=(Tag="Ability.Attack.Enemy",DevComment="")
GameplayTagList=(Tag="Ability.Enemy",DevComment="")
GameplayTagList=(Tag="Ability.Enemy.text",DevComment="")
GameplayTagList=(Tag="Ability.Test",DevComment="")
GameplayTagList=(Tag="Effect.Test",DevComment="")
GameplayTagList=(Tag="Effect.Test1",DevComment="")
GameplayTagList=(Tag="Effect.Test2",DevComment="")

